### ISSUE TITLE
[capitulo 01] - var, let e const

### ISSUE THREAD

**Issue by nathpaiva** [nathpaiva/mentoria#13]
No primeiro capitulo, os exemplos são dados utilizando `var`.

Você sabe a diferença entre `var`, `let` e `const`?

Como você mudaria o código para utilizar `let` ou `const`?

**Comment by fesanto** [comment]
1. Você sabe a diferença entre var, let e const?
**var**, **let** e **const** são palavras-chave para a declaração de variáveis e todas tem escopo de função.
**var** tem escopo de função e escopo global, ou seja, ela pode ser identificada e modificada, inclusive sobrescrita, em qq parte da função. 
**let** e **const** tem escopo de função e de bloco, ou seja, têm escopo específico e não existem fora de onde foram declaradas.
**var** e **let** podem ser reatribuídas, ou seja, receber um conteúdo diferente daquele recebido quando de sua declaração, enquanto que a **const** não aceita reatribuição. Isso não quer dizer que seu conteúdo não possa ser modificado, pois quando se trata de objetos e arrays, é possível fazer uma reatribuição através das propriedades/index. 

2. Como você mudaria o código para utilizar let ou const?
No código do livro eu mudaria tudo para **const** para evitar usar **var**. Usaria **let** apenas se necessário.

3. O que é hoisting?
O **hoisting** é o processo de elevação da **var** ao início do código quando este é executado. O JS as trata como se tivessem sido declaradas no topo do escopo da função ou do escopo global.  Neste caso, é possível atribuir qq valor anteriormente à sua declaração. No caso da **let,** ela precisa ser declarada antes de qualquer atribuição/manipulação. No caso da **const**, uma atribuição deve ser obrigatoriamente feita quando da declaração.
