### ISSUE TITLE
Duvidas

### ISSUE THREAD

**Issue by anaclaudiasilva** [nathpaiva/mentoria#2]
Nath, estou em duvida se o PR eu tenho q mandar aqui mesmo ou no fork que criei no meu perfil, deixei um PR em cada por garantia, mas ainda to me confundindo muito nesse github kkkkk

**Comment by nathpaiva** [comment]
oi @anaclaudiasilva, tudo bem?

Pode criar a PR para esse `repo` mesmo, porque dessa forma ela aparece pra mim e conta como contribuição open source para você.

> conta como contribuição open source para você
Isso é legal pois dessa forma, as pessoas podem ver que você sabe como trabalhar com esse tipo de projeto.

Ó, você consegue ver a sua alteração no repositório [GitBlame](https://github.com/nathpaiva/mentoria/blame/main/ana-claudia/cangaceiro-javascript/client/app/index.js).

Você criando pra você, é uma forma de você ter uma cópia do projeto só para você. 

Se você quiser, podemos marcar um call pra gente passar pelo github e eu tirar suas dúvidas ou explicar como funciona.

Ps. caso eu demore para reponder, pode mandar mensagem pra mim 😉

**Comment by anaclaudiasilva** [comment]
Oi @nathpaiva, tudo bem e com voce?

Entendido, vou tentar subir mais algumas coisas referente ao proximo capítulo entao, e qualquer outra dúvida que for me surgindo eu te aviso e podemos marcar uma call sim.

Por enquanto, muitooo obrigada!!
